apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/ingress

patches:
  - path: backend/replicas.yaml
  - path: frontend/replicas.yaml


images:
  - name: loan_app_backend 
    newName: 612069931326.dkr.ecr.ap-south-1.amazonaws.com/loan_app_backend 
    newTag: latest
  - name: loan_app_frontend
    newName: 612069931326.dkr.ecr.ap-south-1.amazonaws.com/loan_app_frontend
    newTag: latest
